#!/bin/bash
# orangeprint-upgrade - Actualizar scripts orangeprint.
# by carlymx@gmail.com
# Project: https://github.com/carlymx/orangeprint

dialog --backtitle "OrangePrint Upgrade [v.0.0.1.6a]" \
       --title "Actualización de los Scripts:" \
       --msgbox "Vamos a descargar los scripts de Orangeprint" 20 40

sleep 1
clear
rm -rfv ~/scripts/orangeprint/orangeprint-*
wget -P ~/scripts/orangeprint/ https://raw.githubusercontent.com/carlymx/orangeprint/master/scripts/orangeprint/orangeprint-upgrade
wget -P ~/scripts/orangeprint/ https://raw.githubusercontent.com/carlymx/orangeprint/master/scripts/orangeprint/orangeprint-help
wget -P ~/scripts/orangeprint/ https://raw.githubusercontent.com/carlymx/orangeprint/master/scripts/orangeprint/orangeprint-config
chmod +x ~/scripts/orangeprint/orangeprint-*

dialog --backtitle "OrangePrint Upgrade [v.0.0.1.6a]" \
       --title "Actualización de los Scripts:"
       --msgbox "Scripts Actualizados." 20 40
clear
