#!/bin/bash
# orangeprint-help.sh - Un Archivo de ayuda.
# by carlymx@gmail.com
# project: https://github.com/carlymx/orangeprint

dialog  --backtitle "OrangePrint Help [v.0.0.3a]" \
        --title "Sobre OrangePrint" \
        --msgbox "Orangeprint: \n Este es un proyecto donde se intenta crear una compilación de diferentes elementos para poder controlar impresoras RepRap con el software Octoprint en micro computadoras Orange Pi (Zero). \n Actualmente este y otros scripts estan en fase de desarroyo, disculpe las molestias" 10 50
sleep 1
clear
