#!/bin/bash
# orangeprint-config.
# by carlymx@gmail.com
# Project: https://github.com/carlymx/orangeprint

# Ventana de bienvenida.
dialog  --backtitle "OrangePrint Config [v.0.0.2]" \
        --title "¡¡ Importante: !!" \
        --msgbox "Si esta usando una OPi con procesador potente como un H6 (OrangePi 3) o superior es posible que pueda controlar mas de una impresora a la vez sin problemas, para ello hay que instalar y ejecutar tantos Octoprint como impresoras quiera controlar. Este script le pedira que seleccione la cantidad de Instancias activas que quiere iniciar con el sistema." 20 40 

# Ventana que pregunta cuantas instancias se quieren activar.
# Variable que contiene los parametros de la ventana:
instancias=(dialog
        --backtitle "OrangePrint Config [v.0.0.2]"
        --title "Instancias Activas Octoprint"
        --menu "Seleccione la cantidad de Instancias de Octoprint que quiere usar:" 20 40 10)

# Variable que contiene las opciones posibles a elegir. Su salida sera el numero de la opción elegida (1,2,3...):
opciones=(
        1 " 1 Instancia"
        2 "2 Instancias"
        3 "3 Instancias"
        4 "4 Instancias")

# Función que ejecuta la visualización de la ventana de dialogo:
fun_menu=$("${instancias[@]}" "${opciones[@]}" 2>&1 >/dev/tty)
clear

# Según la elección del usuario se ejecuta el script pertinente:
case $fun_menu in
1)
sudo sed -i '/START=/c START=yes' /etc/default/octoprint1
sudo sed -i '/START=/c START=no' /etc/default/octoprint2
sudo sed -i '/START=/c START=no' /etc/default/octoprint3
sudo sed -i '/START=/c START=no' /etc/default/octoprint4
;;

2)
sudo sed -i '/START=/c START=yes' /etc/default/octoprint1
sudo sed -i '/START=/c START=yes' /etc/default/octoprint2
sudo sed -i '/START=/c START=no' /etc/default/octoprint3
sudo sed -i '/START=/c START=no' /etc/default/octoprint4
;;

3)
sudo sed -i '/START=/c START=yes' /etc/default/octoprint1
sudo sed -i '/START=/c START=yes' /etc/default/octoprint2
sudo sed -i '/START=/c START=yes' /etc/default/octoprint3
sudo sed -i '/START=/c START=no' /etc/default/octoprint4
;;

4)
sudo sed -i '/START=/c START=yes' /etc/default/octoprint1
sudo sed -i '/START=/c START=yes' /etc/default/octoprint2
sudo sed -i '/START=/c START=yes' /etc/default/octoprint3
sudo sed -i '/START=/c START=yes' /etc/default/octoprint4
;;
esac

# Ventana Final.
dialog  --backtitle "OrangePrint Config [v.0.0.2]" \
        --title "Parametros Actualizados." \
        --yesno "\nSe han configurado sus preferencias. \n Para que los cambios surjan efecto debe reiniciar el sistema. \n\n ¿Quiere reiniciar el sistema ahora?" 20 40

ans=$?
if [ $ans -eq 0 ]
then
    sudo reboot
else
    sleep1
    clear
fi

clear

#########################################                                                                                                                                                                                                                                                                                                                                  #               NOTAS:                  #                                                                                                                                                                                                                                                                                                                                  #########################################


# Crea una linea en blanco en el promp
        # echo -e "\n"

# Limpiar pantalla
        # clear

# Hacer una pausa (segundos)
        # sleep 1

